### ISSUE TITLE
Glimesh CTA (Copyright Transfer Agreement)

### ISSUE THREAD

**Issue by Heiwa1580** [Glimesh/company#11]
https://docs.google.com/document/d/1eRtGdOZ-lHv63ShhKt2uIBaPcDDdXMwXUbmlytQlhr8/edit?usp=drivesdk

Any comments, changes, concerns please make them.

My next step is stylization of the document and converting it to a fillable PDF document.

How do we feel about things like Docusign?

**Comment by Heiwa1580** [comment]
@clone1018 I made some changes to the Document and some Stylization. What do you think?

**Comment by Heiwa1580** [comment]
That Github linked posted earlier is where we document the discussion around it so that way the talk doesn't get lost to discord

KruxToday at 5:45 PM
Umm I can comment on those

bubdrumToday at 5:45 PM
The whole 100% ownership thing still doesn't sit quite right with me.  Gotta be a way for the designers to still retain some ability to show their work.

@bubdrum
The whole 100% ownership thing still doesn't sit quite right with me.  Gotta be a way for the designers to still retain some ability to show their work.

JustSimyToday at 5:46 PM
Agreed on that. Still use it in their portfolio.

KruxToday at 5:47 PM
Yeah there has to be someway to make a legal agreement that states that it’s 50% ours and 50% there’s if they make any development or changes that way it will be equal

HeiwaToday at 5:47 PM
Glimesh can issue a license as well

@bubdrum
The whole 100% ownership thing still doesn't sit quite right with me.  Gotta be a way for the designers to still retain some ability to show their work.

HaydenToday at 5:47 PM
I sympathize with this.

KruxToday at 5:48 PM
I’ll write up something with my legal skills and send it via here or DM but I will have to look at some laws and glimesh can issue a license to it or buy rights but if we’re going open source than they should be provided under an open source license

JustSimyToday at 5:49 PM
Yeah that’s what I have been reading into as well.

KruxToday at 5:49 PM
I work legal and development with one of the worlds biggest retailers. They do tons of agreements I can write one
[5:50 PM]
But I would have to get permission to use some of the writing out of other documents

HeiwaToday at 5:50 PM
https://github.com/Glimesh/company/issues/11
GitHub
Glimesh CTA (Copyright Transfer Agreement) · Issue #11 · Glimesh/co...
https://docs.google.com/document/d/1eRtGdOZ-lHv63ShhKt2uIBaPcDDdXMwXUbmlytQlhr8/edit?usp=drivesdk Any comments, changes, concerns please make them. My next step is stylization of the document and c...


JustSimyToday at 5:50 PM
What is your opinion on designers having their own legal documents too?

KruxToday at 5:51 PM
I mean they can have there own legal documents but I’ve studied law so much that I know how that works if they attempt to sue or anything else

JustSimyToday at 5:52 PM
I don’t see anyone who for now designed sue Glimesh in any way. I think all they would wish is they can use their work in their portfolio.

KruxToday at 5:53 PM
Like it would take a lot of work to even sue so like you said I would write in the agreement that the design is solely owned by glimesh but certain rights are given for a portfolio use basis(edited)
[5:53 PM]
Which would be protected under a NDA as well
[5:54 PM]
Sorry mistyped

HeiwaToday at 5:57 PM
After transfer Glimesh grants the original copyright holder rights for continued use of the assets listed in portfolios showing previous work.
[5:57 PM]
How does that sound?

**Comment by Heiwa1580** [comment]
@clone1018 i believe all parties involved were fine with this wording and setup. 

Unless you have anything you want to change would you like to close this issue?

**Comment by KruxGamingTV** [comment]
This looks pretty smooth and on point.

**Comment by clone1018** [comment]
Sorry for the delay, looked through it and left some adjustments for you @Heiwa1580.

**Comment by Heiwa1580** [comment]
All adjustments made.
